# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`App-GhaInstall`
	:runtime-requirement    [ :on "perl 5.006"^^:CpanId ];
	:test-requirement       [ :on "Test::More"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

